import { IconType } from 'react-icons';
import {
  SiAxios,
  SiCypress,
  SiDocker,
  SiExpo,
  SiExpress,
  SiFirebase,
  SiGit,
  SiGmail,
  SiJavascript,
  SiJest,
  SiMacpaw,
  SiMongodb,
  SiNextdotjs,
  SiNodedotjs,
  SiPostgresql,
  SiPostman,
  SiPrisma,
  SiPython,
  SiReact,
  SiStripe,
  SiTailwindcss,
  SiTypescript,
  SiZod,
} from 'react-icons/si';

import { FaGithub, FaGoogle, FaLinkedin, FaWhatsapp } from 'react-icons/fa';

export const iconMap: Record<string, IconType> = {
  typescript: SiTypescript,
  javascript: SiJavascript,
  react: SiReact,
  nextjs: SiNextdotjs,
  tailwind: SiTailwindcss,
  nodejs: SiNodedotjs,
  express: SiExpress,
  python: SiPython,
  mongodb: SiMongodb,
  postgresql: SiPostgresql,
  git: SiGit,
  jest: SiJest,
  cypress: SiCypress,
  postman: SiPostman,
  docker: SiDocker,
  firebase: SiFirebase,
  google: FaGoogle,
  gmail: SiGmail,
  github: FaGithub,
  linkedin: FaLinkedin,
  stripe: SiStripe,
  expo: SiExpo,
  whatsapp: FaWhatsapp,
  zod: SiZod,
  axios: SiAxios,
  prisma: SiPrisma,
  zustand: SiMacpaw,
};

export type IconKey = keyof typeof iconMap;
